/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.oscar

import com.amazonaws.services.lambda.runtime.Context
import com.amazonaws.services.lambda.runtime.RequestHandler
import com.twilio.Twilio
import com.twilio.http.TwilioRestClient
import com.twilio.rest.api.v2010.account.Call
import com.twilio.twiml.VoiceResponse
import com.twilio.twiml.voice.Say
import com.twilio.type.PhoneNumber
import com.twilio.type.Twiml

class App : RequestHandler<HandlerInput, HandlerOutput> {

    override fun handleRequest(input: HandlerInput?, context: Context?): HandlerOutput {
        input?.let {
            Twilio.init("ACa83b14233039bc31ab5b3aa8f0b37cc2", "94c8b9a9fb2dafacaed22cb25e9397db")
            val response = VoiceResponse.Builder().say(Say.Builder("Hello! Your name is ${it.message}!, Nice to talk to you! Have a great day!").build()).build()
            Call.creator(
                    PhoneNumber("+16475219058"),
                    PhoneNumber("+13212079452"),
                    Twiml(response.toXml())
            ).create()
            return HandlerOutput("Success!")
        }
        return HandlerOutput("No name found! Sorry!")
    }
}